import type { SecretEntry, CharacterToken, PhoneticProfile } from '../../types';
import { CharacterTable } from '../CharacterTable/CharacterTable';
import { PhoneticTable } from '../PhoneticTable/PhoneticTable';
import { tokenize } from '../../lib/phonetic';
import styles from './PrintSheet.module.css';

interface PrintSheetProps {
  entry: SecretEntry;
  profile: PhoneticProfile;
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

const CATEGORY_LABELS: Record<NonNullable<SecretEntry['category']>, string> = {
  password: 'Password',
  'recovery-code': 'Recovery Code',
  'seed-fragment': 'Seed Fragment',
  'api-key': 'API Key',
  wifi: 'Wi-Fi Password',
  other: 'Other',
};

export function PrintSheet({ entry, profile }: PrintSheetProps) {
  const secret = entry.secretPlaintext ?? '';
  const tokens: CharacterToken[] = secret ? tokenize(secret, profile) : [];

  return (
    <div className={styles.sheet}>
      <div className={styles.printHeader}>
        <div className={styles.printHeaderLeft}>
          <h1 className={styles.printTitle}>{entry.title ?? 'Untitled Secret'}</h1>
          {entry.category && (
            <span className={styles.printCategory}>{CATEGORY_LABELS[entry.category]}</span>
          )}
        </div>
        <div className={styles.printHeaderRight}>
          <div className={styles.printMeta}>
            <span className={styles.printLabel}>Printed:</span>{' '}
            <span>{formatDate(new Date().toISOString())}</span>
          </div>
          <div className={styles.printMeta}>
            <span className={styles.printLabel}>Created:</span>{' '}
            <span>{formatDate(entry.createdAt)}</span>
          </div>
          <div className={styles.printMeta}>
            <span className={styles.printLabel}>Profile:</span>{' '}
            <span>{profile.label}</span>
          </div>
        </div>
      </div>

      <div className={styles.printWarning}>
        Keep this document in a safe, private location. Destroy when no longer needed.
      </div>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Exact Value</h2>
        <div className={styles.exactBox}>
          <div className={styles.exactValue}>{secret || <em>(empty)</em>}</div>
          <div className={styles.exactMeta}>{secret.length} characters</div>
        </div>
      </section>

      {entry.notes && (
        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>Notes</h2>
          <div className={styles.notesBox}>{entry.notes}</div>
        </section>
      )}

      {tokens.length > 0 && (
        <>
          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>Character Breakdown</h2>
            <CharacterTable tokens={tokens} />
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>Phonetic Pronunciation ({profile.label})</h2>
            <PhoneticTable tokens={tokens} />
          </section>
        </>
      )}

      <div className={styles.printFooter}>
        <span>Generated by PaperKey</span>
        <span className={styles.footerSeparator}>•</span>
        <span>All data stayed in your browser</span>
        <span className={styles.footerSeparator}>•</span>
        <span>Entry ID: {entry.id.slice(0, 8)}</span>
      </div>
    </div>
  );
}
